/** GADM HASC_1 → API state id (`1`…`27`). Mirrors Flutter `kHascToHeatmapStateId`. */
export const HASC_TO_STATE_ID: Record<string, string> = {
  'UA.VI': '1',
  'UA.VO': '2',
  'UA.DP': '3',
  'UA.DT': '4',
  'UA.ZT': '5',
  'UA.ZK': '6',
  'UA.ZP': '7',
  'UA.IF': '8',
  'UA.KV': '9',
  'UA.KH': '10',
  'UA.LH': '11',
  'UA.LV': '12',
  'UA.MY': '13',
  'UA.OD': '14',
  'UA.PL': '15',
  'UA.RV': '16',
  'UA.SM': '17',
  'UA.TP': '18',
  'UA.KK': '19',
  'UA.KS': '20',
  'UA.KM': '21',
  'UA.CK': '22',
  'UA.CV': '23',
  'UA.CH': '24',
  'UA.KC': '25',
  'UA.KR': '26',
  'UA.SC': '27',
};
