import type { ThemeColors } from './types';
import { neptunPalette as p } from './neptunPalette';

/** Pure dark iOS settings style. */
export const darkColors: ThemeColors = {
  background: p.darkBackground,
  backgroundSecondary: p.darkGrouped,
  surface: p.darkGrouped,
  surfaceElevated: p.darkElevated,
  surfaceSoft: p.darkElevated,
  surfaceGlass: p.darkGrouped,
  surfaceGlassStrong: p.darkElevated,
  surfaceHighlight: 'rgba(255,255,255,0.06)',
  chrome: p.darkBackground,
  input: p.darkGrouped,
  overlay: 'rgba(0,0,0,0.55)',
  scrim: 'rgba(0,0,0,0.35)',
  textPrimary: p.darkTextPrimary,
  textSecondary: 'rgba(235,235,245,0.72)',
  textMuted: p.darkTextMuted,
  textFaint: 'rgba(142,142,147,0.65)',
  textInverse: p.darkBackground,
  border: p.darkBorder,
  borderStrong: 'rgba(255,255,255,0.18)',
  divider: p.darkDivider,
  primary: p.linkDark,
  primarySoft: 'rgba(10,132,255,0.16)',
  primaryMuted: 'rgba(255,255,255,0.08)',
  success: p.success,
  successMuted: 'rgba(52,199,89,0.16)',
  successSoft: 'rgba(52,199,89,0.10)',
  warning: p.warning,
  warningMuted: 'rgba(255,149,0,0.16)',
  warningSoft: 'rgba(255,149,0,0.10)',
  danger: p.danger,
  dangerMuted: 'rgba(255,59,48,0.16)',
  dangerSoft: 'rgba(255,59,48,0.10)',
  pro: p.proGoldDark,
  proSoft: p.proGoldSoft,
  telegram: p.iosTealDark,
  premium: p.proGoldDark,
  premiumDeep: '#B8860B',
  premiumMuted: 'rgba(255,214,10,0.12)',
  premiumSoft: 'rgba(255,214,10,0.08)',
  card: p.darkGrouped,
  cardMuted: p.darkBackground,
  cardElevated: p.darkElevated,
  bottomNavBackground: p.darkBackground,
  tabActiveBackground: 'transparent',
  tabActiveText: p.darkTextPrimary,
  tabInactiveText: p.darkTextMuted,
  live: p.iosGreenDark,
  threatLow: p.darkTextMuted,
  threatMedium: p.warning,
  threatHigh: p.danger,
  threatCritical: p.iosRedDark,
  mapAlarm: p.danger,
  mapDrone: p.warning,
  mapMissile: p.danger,
  mapAviation: p.iosTealDark,
  mapFire: p.warning,
  statusBarStyle: 'light',
  onAccent: p.darkTextPrimary,
};
