import type { ThemeColors } from './types';
import { neptunPalette as p } from './neptunPalette';

/** Grouped list — gray canvas, white cards. */
export const lightColors: ThemeColors = {
  background: p.lightCanvas,
  backgroundSecondary: p.lightCanvas,
  surface: p.lightBackground,
  surfaceElevated: p.lightBackground,
  surfaceSoft: p.lightCanvas,
  surfaceGlass: p.lightBackground,
  surfaceGlassStrong: p.lightBackground,
  surfaceHighlight: 'rgba(0,0,0,0.04)',
  chrome: p.lightCanvas,
  input: p.lightBackground,
  overlay: 'rgba(0,0,0,0.28)',
  scrim: 'rgba(0,0,0,0.16)',
  textPrimary: p.lightTextPrimary,
  textSecondary: 'rgba(60,60,67,0.72)',
  textMuted: p.lightTextMuted,
  textFaint: 'rgba(142,142,147,0.55)',
  textInverse: p.lightBackground,
  border: p.lightBorder,
  borderStrong: 'rgba(60,60,67,0.22)',
  divider: p.lightDivider,
  primary: p.link,
  primarySoft: 'rgba(0,122,255,0.12)',
  primaryMuted: 'rgba(0,0,0,0.06)',
  success: p.success,
  successMuted: 'rgba(52,199,89,0.12)',
  successSoft: '#F0FDF4',
  warning: p.warning,
  warningMuted: 'rgba(255,149,0,0.12)',
  warningSoft: '#FFF7ED',
  danger: p.danger,
  dangerMuted: 'rgba(255,59,48,0.12)',
  dangerSoft: '#FEF2F2',
  pro: '#B8860B',
  proSoft: 'rgba(255,214,10,0.20)',
  telegram: p.iosTeal,
  premium: '#B8860B',
  premiumDeep: '#996515',
  premiumMuted: 'rgba(255,214,10,0.14)',
  premiumSoft: 'rgba(255,214,10,0.10)',
  card: p.lightBackground,
  cardMuted: p.lightCanvas,
  cardElevated: p.lightBackground,
  bottomNavBackground: p.lightBackground,
  tabActiveBackground: 'transparent',
  tabActiveText: p.lightTextPrimary,
  tabInactiveText: p.lightTextMuted,
  live: p.iosGreen,
  threatLow: p.lightTextMuted,
  threatMedium: p.warning,
  threatHigh: p.danger,
  threatCritical: p.iosRed,
  mapAlarm: p.danger,
  mapDrone: p.warning,
  mapMissile: p.danger,
  mapAviation: p.iosTeal,
  mapFire: p.warning,
  statusBarStyle: 'dark',
  onAccent: p.lightBackground,
};
