import type { TextStyle, ViewStyle } from 'react-native';
import type { radii, spacing, typography } from './tokens';

export type ThemeMode = 'light' | 'dark' | 'system';

export type ResolvedScheme = 'light' | 'dark';

export type ThemeColors = {
  background: string;
  backgroundSecondary: string;
  surface: string;
  surfaceElevated: string;
  surfaceSoft: string;
  surfaceGlass: string;
  surfaceGlassStrong: string;
  surfaceHighlight: string;
  chrome: string;
  input: string;
  overlay: string;
  scrim: string;
  textPrimary: string;
  textSecondary: string;
  textMuted: string;
  textFaint: string;
  textInverse: string;
  border: string;
  borderStrong: string;
  divider: string;
  primary: string;
  /** Tinted surface behind primary actions (not link text). */
  primarySoft: string;
  primaryMuted: string;
  pro: string;
  proSoft: string;
  telegram: string;
  success: string;
  successMuted: string;
  successSoft: string;
  warning: string;
  warningMuted: string;
  warningSoft: string;
  danger: string;
  dangerMuted: string;
  dangerSoft: string;
  premium: string;
  premiumDeep: string;
  premiumMuted: string;
  premiumSoft: string;
  card: string;
  cardMuted: string;
  cardElevated: string;
  bottomNavBackground: string;
  tabActiveBackground: string;
  tabActiveText: string;
  tabInactiveText: string;
  live: string;
  threatLow: string;
  threatMedium: string;
  threatHigh: string;
  threatCritical: string;
  mapAlarm: string;
  mapDrone: string;
  mapMissile: string;
  mapAviation: string;
  mapFire: string;
  statusBarStyle: 'light' | 'dark';
  onAccent: string;
};

export type ThemeShadows = {
  sm: ViewStyle;
  md: ViewStyle;
  sheet: ViewStyle;
  glowAccent: ViewStyle;
};

export type RadarThemeTokens = {
  bg: string;
  bgSecondary: string;
  surface: string;
  card: string;
  border: string;
  accent: string;
  accentSoft: string;
  live: string;
  warning: string;
  danger: string;
  text: string;
  textSecondary: string;
  textMuted: string;
  padH: number;
  cardPad: number;
  cardRadius: number;
  chipRadius: number;
  cardGap: number;
  sectionGap: number;
};

export type ChatThemeTokens = {
  bg: string;
  ambientTop: readonly [string, string, string];
  ambientBottom: readonly [string, string];
  surfaceGlass: string;
  surfaceInput: string;
  border: string;
  borderStrong: string;
  divider: string;
  text: string;
  textSoft: string;
  textMuted: string;
  textFaint: string;
  accent: string;
  accentSoft: string;
  accentMuted: string;
  onAccent: string;
  premium: string;
  danger: string;
  success: string;
  radiusBubble: number;
  radiusBubbleTail: number;
  radiusComposer: number;
  radiusPill: number;
  radiusGate: number;
  bubbleMine: string;
  bubbleOther: string;
  bubbleSystem: string;
  shadowBubble: ViewStyle;
  type: {
    roomTitle: TextStyle;
    roomSub: TextStyle;
    message: TextStyle;
    meta: TextStyle;
    composer: TextStyle;
    filter: TextStyle;
  };
};

export type ProfileThemeTokens = {
  screenBg: string;
  ambientTop: readonly [string, string];
  cardBg: string;
  cardBgElevated: string;
  cardBorder: string;
  cardShadow: string;
  heroGradient: readonly [string, string];
  heroRing: string;
  premiumGradient: readonly [string, string, string];
  premiumGradientSoft: readonly [string, string];
  premiumAccent: string;
  premiumGlow: string;
  freeBg: string;
  freeText: string;
  statusCalm: string;
  iconBg: string;
  divider: string;
  sectionLabel: string;
  textPrimary: string;
  textSecondary: string;
  textTertiary: string;
  radiusCard: number;
  radiusRow: number;
  radiusAvatar: number;
  avatarSize: number;
  insetH: number;
  sectionGap: number;
  rowPadV: number;
  groupGap: number;
};

/** Legacy palette shape used across existing screens. */
export type LegacyPalette = {
  bg: string;
  bgElevated: string;
  bgChrome: string;
  surface: string;
  surfaceRaised: string;
  surfaceGlass: string;
  surfaceGlassStrong: string;
  surfaceHighlight: string;
  input: string;
  overlay: string;
  scrim: string;
  border: string;
  borderStrong: string;
  divider: string;
  text: string;
  textSoft: string;
  textMuted: string;
  textFaint: string;
  tabInactive: string;
  accent: string;
  accentSoft: string;
  accentMuted: string;
  success: string;
  successMuted: string;
  warning: string;
  warningMuted: string;
  danger: string;
  dangerMuted: string;
  premium: string;
  premiumDeep: string;
  premiumMuted: string;
  mapAlarm: string;
  mapDrone: string;
  mapMissile: string;
  mapAviation: string;
  mapFire: string;
};

export type LegacyColors = {
  bg: string;
  bg2: string;
  surface: string;
  surface2: string;
  surfaceGlass: string;
  inputBg: string;
  border: string;
  borderStrong: string;
  text: string;
  textSoft: string;
  muted: string;
  tabInactive: string;
  accent: string;
  accent2: string;
  success: string;
  warning: string;
  danger: string;
  premium: string;
  mapAlarm: string;
  mapDrone: string;
  mapMissile: string;
  mapAviation: string;
  mapFire: string;
};

export type AppTheme = {
  scheme: ResolvedScheme;
  colors: ThemeColors;
  palette: LegacyPalette;
  legacyColors: LegacyColors;
  radar: RadarThemeTokens;
  chat: ChatThemeTokens;
  profile: ProfileThemeTokens;
  shadows: ThemeShadows;
  glass: { card: ViewStyle; chrome: ViewStyle };
  radii: typeof radii;
  spacing: typeof spacing;
  typography: typeof typography;
};
